### ISSUE TITLE
GetStateKeys before deploying a contract

### ISSUE THREAD

**Issue by lacabra** [enigmampc/enigma-p2p#136]
The P2P needs to call `GetStateKeys` with the deterministic contract address that is about to be deployed, otherwise `core` throws the error.
```
Error in deployment of smart contract function: Cryptography Error: MissingKeyError { key_type: "State Key" }
```

So right after P2P has verified the deployment task is indeed addressed to this worker, and right before sending the deployment task to `core`, it should execute, something along the lines of:
```
controller.execCmd(constants.NODE_NOTIFICATIONS.GET_STATE_KEYS, {addresses: ['address_of_contract_to_be_deployed',]});
```

How to reproduce
------------------
In the integration test, run the following:
1. `01_init.spec.js`
2. `02_deploy_calculator.spec.js`
3. `02_deploy_flipcoin.spec.js`

The first contract deployment succeeds because it runs a modified version of the P2P that knows the first contract address and requests the state keys in advance [here](https://github.com/enigmampc/enigma-p2p/blob/aeb50619fffc4ac891d438cb589e49ffe3d3543a/src/cli/cli_app.js#L411) (only documented here for the sake of completeness, but you could disregard this hack and focus on the error that is triggered in the following step). But the error in question reveals itself when you attempt the second deployment because it does not request the state keys it needs.

**Comment by lenak25** [comment]
Thanks for identifying this @lacabra . 
Today the P2P triggers the PTT action only when a new epoch starts, so indeed a newly deployed contract doesn't initiate keys update. 
I will address this, thanks!
