### ISSUE TITLE
When wrongWorker, P2P should mark the task as failed

### ISSUE THREAD

**Issue by lacabra** [enigmampc/enigma-p2p#194]
**Describe the bug**
When a `p2p` instance receives a task that is not meant for her, it currently displays an error but does not inform the network/client. Instead it should mark that task as `FAILED` otherwise it will remain as pending forever.

Here's the current output from the network:
```
p2p_1        | [Fri May 10 2019 16:05:05 GMT+0000 (Coordinated Universal Time)] INFO [VERIFY_NEW_TASK] error in verification of task 0xffd02e0de1519a4f16f2841ed264443f5a5bbdf555d855b8bda1801b5096f650: WorkerSelectionVerificationErr: Not the selected worker for the 88987af7d35eabcad95915b93bfd3d2bc3308f06b7197478b0dfca268f0497dc task
p2p_1        | [Fri May 10 2019 16:05:05 GMT+0000 (Coordinated Universal Time)] DEBUG [VERIFY:] task 0xffd02e0de1519a4f16f2841ed264443f5a5bbdf555d855b8bda1801b5096f650 not verified
```

**To Reproduce**
1. Launch the integration tests network with NODES > 1: `NODES=2 ./launch.bash`
2. Execute the following tests:
```
01_init.spec.js
03_deploy_fail_wrongworker.spec.js
```
On the client, you have to be on branch `wrongWorker` from [PR 99](https://github.com/enigmampc/enigma-contract/pull/99) otherwise the second test file is not available.

**Expected behavior**
Upon failing to verify the task, the `p2p` instance should submit a `FAILED` task to the contract and the network.

**Comment by lenak25** [comment]
Thanks @lacabra for raising this.

I am not sure this is indeed a bug. If a wrong worker receives a task which doesn't meant for it, it does not mean that the right worker hadn't received it and started the computation.

**Comment by lacabra** [comment]
This issue can be closed as this is the intended behavior of the network. The integration tests will trigger this scenario and then wait for a timeout to ensure that no computation is triggered.
