### ISSUE TITLE
Parallel handling of PTT and compute tasks leads to core error

### ISSUE THREAD

**Issue by lacabra** [enigmampc/enigma-p2p#218]
**Describe the bug**
When the blockchain is one block from an epoch change. A computation is initiated, and the first tx of that computation (the creation of the task record) triggers an epoch change. The KM triggers the change, and the worker assigned to that computation gets notified of the change and requests new state keys. The first time that the worker hits the KM with a state key request, the request fails because the epoch is unconfirmed, and the worker will retry (with an exponential backoff). In the meantime, the actual computation request hits the worker node, which still doesn’t have the state keys for that contract, and errors out.

The “problem” here is that the `p2p` code handles requests in parallel, and the computation request is unaware that it is waiting for the epoch to confirm, and thus another thread in the p2p node is waiting for those state keys to arrive.

**To Reproduce**
1. Launch the Docker network with `NODES=4 ./launch.bash`
2. On a different terminal, connect to the client container:
```
docker-compose exec client /bin/bash
```
3. Execute the following commands on the client container:
```
./init.bash 
cd enigma-contract/enigma-js/test/integrationTests/
yarn test:integration 01_init.spec.js 
yarn test:integration 02_deploy_voting.spec.js 
yarn test:integration 10_execute_voting.spec.js <-- this one works all fine, but leaves it at block 79, next epoch starting at 80
yarn test:integration 10_execute_voting.spec.js <-- first computation fails
```
which fails with core throwing:
```
core_2      | Error in execution of smart contract function: Cryptography Error: MissingKeyError { key_type: "State Key" }
core_2      | 22:47:57 [INFO] compute_task() => Err(EnclaveFailError { err: KeysError, status: SGX_SUCCESS }
```
though the cause is not in core but in p2p as described above. FYI, there is an element of randomness in trying to reproduce the above due to the exponential backoff retrial. A second time that I tried the steps above, the error did not happen.

**Expected behavior**
`p2p` should either be aware of what other threads are waiting for, or include error handling (the errors coming from `core`) that would prompt it to retry.

**Comment by lenak25** [comment]
Resolved
